= URL Rewriting

Since 5.1.0.2, Tapestry has basic support for URL rewriting.

Incoming requests and links generated by Tapestry can be rewritten using the same API, based on a chain of https://github.com/apache/tapestry-5/blob/5.1.0.1/tapestry-core/src/main/java/org/apache/tapestry5/urlrewriter/URLRewriterRule.java[`org.apache.tapestry5.urlrewriter.URLRewriterRule`] interfaces.
These rules are executed before all other Tapestry request handling, so your application remains unaware that the request was rewritten.

Each `URLRewriterRule` chooses in its `process(Request request)` method between returning another javadoc:org.apache.tapestry5.services.Request[] to effectively rewrite it or returning the received request unchanged, meaning that this rule does not apply to that request.

[NOTE]
====
Tapestry 5.1.0.4 introduced https://github.com/apache/tapestry-5/blob/5.1.0.4/tapestry-core/src/main/java/org/apache/tapestry5/urlrewriter/URLRewriteContext.java[`org.apache.tapestry5.urlrewriter.URLRewriteContext`] to give access to more information about the request, and the examples will use this version.
====

To simplify `Request` creation, Tapestry provides the https://github.com/apache/tapestry-5/blob/5.1.0.4/tapestry-core/src/main/java/org/apache/tapestry5/urlrewriter/SimpleRequestWrapper.java[`org.apache.tapestry5.urlrewriter.SimpleRequestWrapper`] class to wrap an existing `Request` and delegate all methods to it, except for `getPath()` and `getServerName()`.
More request wrappers may be added in the future on demand.

== Configuration

URL rewriting support is configured by contributing https://github.com/apache/tapestry-5/blob/5.1.0.1/tapestry-core/src/main/java/org/apache/tapestry5/urlrewriter/URLRewriterRule.java[`org.apache.tapestry5.urlrewriter.URLRewriterRule`] to the https://github.com/apache/tapestry-5/blob/5.1.0.2/tapestry-core/src/main/java/org/apache/tapestry5/internal/services/URLRewriterService.java[`org.apache.tapestry5.services.URLRewriter`] service.

This example simply rewrites all incoming requests from `/struts` to `/tapestry`.
Add the following code in your `AppModule` or any other Tapestry-IoC module class:

[source,java]
----
public static void contributeURLRewriter(OrderedConfiguration<URLRewriterRule> configuration)
{
  URLRewriterRule rule = new URLRewriterRule() 
  {
    public Request process(Request request, URLRewriteContext context)
    {
      String path = request.getPath();
      if (path.equals("/struts"))
      {
        request = new SimpleRequestWrapper(request, "/tapestry");
      }
      return request;
    }

    public RewriteRuleApplicability applicability()
    {
      return RewriteRuleApplicability.INBOUND;
    }
  };

  configuration.add("myrule", rule);
}
----

== Rule Chaining

Multiple rules can be contributed and ordered according to their service id.
Add the following code in your `AppModule` or any other Tapestry-IoC module class:

[source,java]
----
public static void contributeURLRewriter(OrderedConfiguration<URLRewriterRule> configuration)
{
  URLRewriterRule strutsToTapestry = new URLRewriterRule() 
  {
    public Request process(Request request, URLRewriteContext context)
    {
      String path = request.getPath();
      if (path.equals("/struts"))
      {
        request = new SimpleRequestWrapper(request, "/tapestry");
      }
      return request;
    }

    public RewriteRuleApplicability applicability()
    {
      return RewriteRuleApplicability.INBOUND;
    }
  };

  URLRewriterRule tapestryToDoc = new URLRewriterRule() 
  {
    public Request process(Request request, URLRewriteContext context)
    {
      String path = request.getPath();
      if (path.equals("/tapestry"))
      {
        request = new SimpleRequestWrapper(request, "/doc");
      }
      return request;
    }

    public RewriteRuleApplicability applicability()
    {
      return RewriteRuleApplicability.INBOUND;
    }
  };

  URLRewriterRule loginToExternal = new URLRewriterRule()
  {
    public Request process(Request request, URLRewriteContext context)
    {
      String serverName = request.getServerName();
      String path = request.getPath();
      if (serverName.equals("localhost") && path.equalsIgnoreCase("/doc/login")) 
      {
        request = new SimpleRequestWrapper(request, "https://login.example.com", "/");
      }
      return request;
    }

    public RewriteRuleApplicability applicability()
    {
      return RewriteRuleApplicability.OUTBOUND;
    }
  };

  configuration.add("strutsToTapestry", strutsToTapestry);
  configuration.add("tapestryToDoc", tapestryToDoc, "before:strutsToTapestry");
  configuration.add("loginToExternal", loginToExternal);
}
----

The first defined rule (`strutsToTapestry`) acts on all requests to `/struts` and rewrites them to `/tapestry` and leaves requests to other URLs unchanged.

The second defined rule (`tapestryToDoc`) rewrites `/tapestry` to `/doc` and runs _before_ `strutsToTapestry`, so that `/struts` won't end up as `/doc`.

The third defined rule (`loginToExternal`) rewrites outbound links generated by Tapestry, like by a `PageLink`, resulting in a tag pointing to `https://login.example.com` for links to the `doc` page with an activation context of `login`.

== Single Rule for Inbound/Outbound

In the following example, we'll reconfigure URLs used to render pages.
Whereas previous examples used separate rules for handling inbound and outbound rewriting, this demonstrates using a single rule for both scenarios.

We assume that every page is named `...Page` (`UserPage`, `TransactionPage`, `IndexPage`, etc.).
This naming convention also means that we don't have to worry about Tapestry's auto-stripping of `index` from URLs, because our page would be `IndexPage`, rather than `Index`.

[source,java]
----
public static void contributeURLRewriter(OrderedConfiguration<URLRewriterRule> configuration)
{
  URLRewriterRule rule = new URLRewriterRule() 
  {
    public Request process(Request request, URLRewriteContext context)
    {
      String path = request.getPath();
      if (context.isIncoming())
      {
        // Don't rewrite component event requests
        if (path.contains(".") || path.contains(":")) 
        {
          return request;
        }

        String pageName = path.substring(1,request.getPath().indexOf('/',1));
        return new SimpleRequestWrapper(request, request.getPath().replaceAll(pageName,pageName + "page"));
      }
      else
      {
        // For component events, getPageParameters() will return null
        if (context.getPageParameters() != null) 
        {
          String pageName = context.getPageParameters().getLogicalPageName().toLowerCase();
          String newPageName = pageName.replaceAll("page$","");
          return new SimpleRequestWrapper(request,path.replaceAll(pageName,newPageName));
        }
      }
      return request;
    }

    public RewriteRuleApplicability applicability()
    {
      return RewriteRuleApplicability.BOTH;
    }
  };

  configuration.add("rule",rule);

}
----

The `context.isIncoming()` determines what kind of request is rewritten.

The `else` branch (= outgoing request) only rewrites page links by retrieving the logical page name and replacing its occurrence in the URL with the shortened form of the link.

This code segment demonstrates how the additional information provided by `URLRewriteContext` can be used to rewrite URLSs in a generalized manner.

[NOTE]
====
`URLRewriteContext#getPageParameters()` only returns non-`null` when `process` is called due to page link creation.
The same is true for `URLRewriteContext#getComponentEventParameters()` and component event link creation.
====
